### ISSUE TITLE
Biomass Crash

### ISSUE THREAD

**Issue by macroblitz** [DarkWyvren/Pixel_Texturepack_Mindustry#42]
It gives a crash on [biomass synthesis facility] after launching. When I disabled the mod, it didn't crash anymore.

`Mindustry has crashed. How unfortunate.
Version: steam build 146
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4082mb
Cores: 8
Mods: betamindy-music:1.0, time-control:0.2, xelos-pixel-texturepack:0.4.1

mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveIO.load(SaveIO.java:152)
	at mindustry.maps.generators.FileMapGenerator.generate(FileMapGenerator.java:47)
	at mindustry.core.World.lambda$loadSector$2(World.java:266)
	at mindustry.core.World.loadGenerator(World.java:251)
	at mindustry.core.World.loadSector(World.java:264)
	at mindustry.core.World.loadSector(World.java:257)
	at mindustry.core.Control.playNewSector(Control.java:515)
	at mindustry.core.Control.lambda$playSector$33(Control.java:508)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:268)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.io.IOException: Error reading region "map".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:98)
	at mindustry.io.versions.LegacyRegionSaveVersion.read(LegacyRegionSaveVersion.java:24)
	at mindustry.io.SaveIO.load(SaveIO.java:167)
	at mindustry.io.SaveIO.load(SaveIO.java:145)
	... 13 more
Caused by: java.io.IOException: Could not skip bytes. Expected length: 65535; Actual length: 53
	at mindustry.io.SaveFileReader.skipChunk(SaveFileReader.java:177)
	at mindustry.io.SaveVersion.readMap(SaveVersion.java:321)
	at mindustry.io.versions.LegacyRegionSaveVersion.lambda$read$1(LegacyRegionSaveVersion.java:24)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:164)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:157)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:96)
	... 16 more
`

**Comment by itproot** [comment]
[Xeloboyo-Factoriodustry-5e3dc89.zip](https://github.com/user-attachments/files/18041454/Xeloboyo-Factoriodustry-5e3dc89.zip)
i commented up some code in main.js, it shouldn't crash anymore
